{{- if .Values.kubearmorrelay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: kubearmor-relay
  name: kubearmor-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: kubearmor-relay
    spec:
      containers:
      - image: {{- if eq .Values.environment.name "aws" }} {{printf "%s:%s" .Values.kubearmorRelay.image.repository .Values.version}} {{- else if eq .Values.environment.name "oke"}} {{printf "%s:%s" .Values.kubearmorRelay.image.repository .Values.version}} {{- else}} {{printf "%s:%s" .Values.kubearmorRelay.image.repository .Values.kubearmorRelay.image.tag}} {{- end}}
        name: kubearmor-relay-server
        ports:
        - containerPort: 32767
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kubearmor
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorAnnotationManager.name }}
  name: {{ .Values.kubearmorAnnotationManager.name }}
  
spec:
  replicas: {{ .Values.kubearmorAnnotationManager.replicas }}
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorAnnotationManager.name }}
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/manager: unconfined
      labels:
        kubearmor-app: {{ .Values.kubearmorAnnotationManager.name }}
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: {{- if eq .Values.environment.name "aws" }} {{printf "%s:%s" .Values.kubearmorAnnotationManager.image.repository .Values.version}} {{- else if eq .Values.environment.name "oke"}} {{printf "%s:%s" .Values.kubearmorAnnotationManager.image.repository .Values.version}} {{- else}} {{printf "%s:%s" .Values.kubearmorAnnotationManager.image.repository .Values.kubearmorAnnotationManager.image.tag}} {{- end}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /sys/kernel/security
          name: sys-path
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{printf "%s:%s" .Values.kubeRbacProxy.image.repository .Values.kubeRbacProxy.image.tag}}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      serviceAccountName: {{ .Values.kubearmorAnnotationManager.name }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.kubearmorAnnotationManager.name }}
      - hostPath:
          path: /sys/kernel/security
          type: Directory
        name: sys-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
  name: {{ .Values.kubearmorPolicyManager.name}}
  
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{printf "%s:%s" .Values.kubeRbacProxy.image.repository .Values.kubeRbacProxy.image.tag}}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: {{- if eq .Values.environment.name "aws" }} {{printf "%s:%s" .Values.kubearmorPolicyManager.image.repository .Values.version}} {{- else if eq .Values.environment.name "oke"}} {{printf "%s:%s" .Values.kubearmorPolicyManager.image.repository .Values.version}} {{- else}} {{printf "%s:%s" .Values.kubearmorPolicyManager.image.repository .Values.kubearmorPolicyManager.image.tag}} {{- end}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: {{ .Values.kubearmorPolicyManager.name }}
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: {{ .Values.kubearmorPolicyManager.name}}
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
  name: {{ .Values.kubearmorHostPolicyManager.name}}
  
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{printf "%s:%s" .Values.kubeRbacProxy.image.repository .Values.kubeRbacProxy.image.tag}}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: {{- if eq .Values.environment.name "aws" }} {{printf "%s:%s" .Values.kubearmorHostPolicyManager.image.repository .Values.version}} {{- else if eq .Values.environment.name "oke"}} {{printf "%s:%s" .Values.kubearmorHostPolicyManager.image.repository .Values.version}} {{- else}} {{printf "%s:%s" .Values.kubearmorHostPolicyManager.image.repository .Values.kubearmorHostPolicyManager.image.tag}} {{- end}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: {{ .Values.kubearmorHostPolicyManager.name }}
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      # both kubearmor-policy and kubearmor-host-policy deployments share same service account      
      serviceAccountName: {{ .Values.kubearmorPolicyManager.name}} 
      terminationGracePeriodSeconds: 10