# Default values for kubearmor.
# Declare variables to be passed into your templates.

version: 0.9.0

kubearmorrelay:
  enabled: true

kubearmorInit:
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/accuknox/kubearmor-init

kubearmorRelay:
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/accuknox/kubearmor-relay-server

kubeRbacProxy:
  image: 
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.12.0

kubearmorPolicyManager:
  name: kubearmor-policy-manager
  replicas: 1
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/accuknox/kubearmor-policy-manager

kubearmorHostPolicyManager:
  name: kubearmor-host-policy-manager
  replicas: 1
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/accuknox/kubearmor-host-policy-manager

caps:
  capabilities:
    add:
    - SETUID
    - SETGID
    - SETPCAP
    - SYS_ADMIN
    - SYS_PTRACE
    - MAC_ADMIN
    - SYS_RESOURCE
    - IPC_LOCK
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    drop:
    - ALL
#volume mounts and volumes
kubearmor:
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/accuknox/kubearmor
  commonMounts:
  - mountPath: /opt/kubearmor/BPF
    name: bpf
  commonVolumes:
  - emptyDir: {}
    name: bpf
  initMounts:
  - mountPath: /opt/kubearmor/BPF
    name: bpf
  - mountPath: /lib/modules
    name: lib-modules-path
    readOnly: true
  - mountPath: /sys/fs/bpf
    name: sys-fs-bpf-path
  - mountPath: /sys/kernel/security
    name: sys-kernel-security-path
  - mountPath: /sys/kernel/debug
    name: sys-kernel-debug-path
  - mountPath: /media/root/etc/os-release
    name: os-release-path
    readOnly: true
  - mountPath: /usr/src
    name: usr-src-path
    readOnly: true
  volumeMountsGeneric:
    - mountPath: /usr/src
      name: usr-src-path
      readOnly: true
    - mountPath: /lib/modules
      name: lib-modules-path
      readOnly: true
    - mountPath: /sys/fs/bpf
      name: sys-fs-bpf-path
    - mountPath: /sys/kernel/security
      name: sys-kernel-security-path
    - mountPath: /sys/kernel/debug
      name: sys-kernel-debug-path
    - mountPath: /media/root/etc/os-release
      name: os-release-path
      readOnly: true
    - mountPath: /etc/apparmor.d
      name: etc-apparmor-d-path
    - mountPath: /var/run/containerd/containerd.sock
      name: containerd-sock-path
      readOnly: true
    - mountPath: /run/containerd
      name: containerd-storage-path
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-storage-path
      readOnly: true

  volumesGeneric:
    - hostPath:
        path: /lib/modules
        type: DirectoryOrCreate
      name: lib-modules-path
    - hostPath:
        path: /sys/fs/bpf
        type: Directory
      name: sys-fs-bpf-path
    - hostPath:
        path: /sys/kernel/security
        type: Directory
      name: sys-kernel-security-path
    - hostPath:
        path: /sys/kernel/debug
        type: Directory
      name: sys-kernel-debug-path
    - hostPath:
        path: /etc/os-release
        type: File
      name: os-release-path
    - hostPath:
        path: /usr/src
        type: Directory
      name: usr-src-path
    - hostPath:
        path: /etc/apparmor.d
        type: DirectoryOrCreate
      name: etc-apparmor-d-path
    - hostPath:
        path: /var/run/containerd/containerd.sock
        type: Socket
      name: containerd-sock-path
    - hostPath:
        path: /run/containerd
        type: DirectoryOrCreate
      name: containerd-storage-path
    - hostPath:
        path: /var/lib/docker
        type: DirectoryOrCreate
      name: docker-storage-path

