apiVersion: operator.kubearmor.com/v1
kind: Config
metadata:
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: config-sample
    app.kubernetes.io/part-of: kubearmoroperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubearmoroperator
  name: config-sample
spec:
  # TODO(user): Add fields here
