# kubearmor-ca secret
{{- $ca := genCA "kubearmor"  1095 -}}
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.caSecretName }}
  labels:
    kubearmor-app: kubearmor-ca
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $altNames := list ( printf "kubearmor.%s" .Release.Namespace ) ( printf "kubearmor.%s.svc" .Release.Namespace ) -}}
{{- $cert := genSignedCert "kubearmor-relay" nil $altNames 1095 $ca -}}
# kubearmor-relay-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmorRelay.tls.certSecretName }}
  labels:
    kubearmor-app: kubearmor-relay-certs
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}