// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ConfigListerExpansion allows custom methods to be added to
// ConfigLister.
type ConfigListerExpansion interface{}

// ConfigNamespaceListerExpansion allows custom methods to be added to
// ConfigNamespaceLister.
type ConfigNamespaceListerExpansion interface{}
