apiVersion: v1
data:
  defaultFilePosture: audit
  defaultCapabilitiesPosture: audit
  defaultNetworkPosture: audit
kind: ConfigMap
metadata:
  labels:
    kubearmor-app: kubearmor-configmap
  name: kubearmor-config
  namespace: kube-system