apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    kubearmor-app: kubearmor
  name: kubearmor
  namespace: kube-system
spec:
  selector:
    matchLabels:
      kubearmor-app: kubearmor
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
      labels:
        kubearmor-app: kubearmor
    spec:
      containers:
      - args:
        - -gRPC=32767
        env:
        - name: KUBEARMOR_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBEARMOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.kubearmor.image.repository }}:{{ .Values.version }}"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - if [ -z $(pgrep kubearmor) ]; then exit 1; fi;
          initialDelaySeconds: 60
          periodSeconds: 10
        name: kubearmor
        ports:
        - containerPort: 32767
        securityContext:
          {{ toYaml .Values.caps | nindent 10}}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        {{ toYaml .Values.kubearmor.commonMounts | nindent 10}}
        {{ toYaml .Values.kubearmor.volumeMountsGeneric | nindent 10 }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
      - image: "{{ .Values.kubearmorInit.image.repository }}:{{ .Values.version }}"
        name: init
        securityContext:
          {{ toYaml .Values.caps | nindent 10}}
          privileged: false
        volumeMounts:
        {{ toYaml .Values.kubearmor.initMounts | nindent 10 }}
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccountName: kubearmor
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      {{ toYaml .Values.kubearmor.commonVolumes | nindent 8}}
      {{ toYaml .Values.kubearmor.volumesGeneric | nindent 8 }}
