{{- if .Values.kubearmorrelay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: kubearmor-relay
  name: kubearmor-relay
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: kubearmor-relay
    spec:
      containers:
      - image: "{{ .Values.kubearmorRelay.image.repository }}:{{ .Values.version }}"
        name: kubearmor-relay-server
        ports:
        - containerPort: 32767
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kubearmor
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
  name: {{ .Values.kubearmorPolicyManager.name}}
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: {{ .Values.kubearmorPolicyManager.name}}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}"
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: "{{ .Values.kubearmorPolicyManager.image.repository }}:{{ .Values.version }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: {{ .Values.kubearmorPolicyManager.name }}
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: {{ .Values.kubearmorPolicyManager.name}}
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
  name: {{ .Values.kubearmorHostPolicyManager.name}}
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
      labels:
        kubearmor-app: {{ .Values.kubearmorHostPolicyManager.name}}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}"
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: "{{ .Values.kubearmorHostPolicyManager.image.repository }}:{{ .Values.version }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: {{ .Values.kubearmorHostPolicyManager.name }}
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 20Mi
      # both kubearmor-policy and kubearmor-host-policy deployments share same service account      
      serviceAccountName: {{ .Values.kubearmorPolicyManager.name}} 
      terminationGracePeriodSeconds: 10      