apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubearmorPolicyManager.name }}
  namespace: kube-system