name: ginkgo-test

on: workflow_dispatch
#   push:
#     branches: [main]
#     paths:
#       - "KubeArmor/**"
#       - "tests/**"
#       - "protobuf/**"
#       - ".github/workflows/ci-test-ginkgo.yml"
#   pull_request:
#     branches: [main]
#     paths:
#       - "KubeArmor/**"
#       - "tests/**"
#       - "protobuf/**"
#       - ".github/workflows/ci-test-ginkgo.yml"

jobs:
  build:
    name: Auto-testing Framework / ${{ matrix.os }} / ${{ matrix.runtime }}
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Install the latest LLVM toolchain
        run: ./.github/workflows/install-llvm.sh

      - name: Compile libbpf
        run: ./.github/workflows/install-libbpf.sh

      - name: Setup a Kubernetes environment
        run: ./.github/workflows/install-k3s.sh

      - name: Install an annotation controller
        run: ./.github/workflows/install-annotation-controller.sh

      - name: Run kubectl proxy
        run: kubectl proxy &

      - name: Run KubeArmor in background
        run: |
          make -C KubeArmor/ run &
          bash -c 'for((i=0;i<300;i++)); do cnt=$(ps -e | grep kubearmor | wc -l); [[ $cnt -gt 0 ]] && echo "Kubearmor is running" && break; sleep 1; done'
        timeout-minutes: 5

      - name: Test KubeArmor using Ginkgo
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          make -C tests/
        timeout-minutes: 15
